# Generated by Django 3.0.7 on 2020-06-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0003_auto_20200610_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='imb_rating',
            new_name='imdb_rating',
        ),
    ]
